(()=>{
'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const KEY='grip.household.v4', DONE='grip.done.v4', THEME='grip.theme.v1';
const euro=new Intl.NumberFormat('nl-NL',{style:'currency',currency:'EUR',maximumFractionDigits:0});
const money=n=>euro.format(Number(n)||0), signed=n=>(n>=0?'+ ':'- ')+money(Math.abs(n));
const raw=id=>Number($('#'+id)?.value)||0, nonneg=id=>Math.max(0,raw(id)), clamp=(n,a,b)=>Math.min(b,Math.max(a,n));
let bills=[];
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(t._timer);t._timer=setTimeout(()=>t.classList.remove('show'),2200)}
function switchTab(name){$$('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));$$('.panel').forEach(p=>p.classList.toggle('active',p.id==='panel-'+name));if(name==='scenario')renderScenarioBase()}
$$('.tab').forEach(b=>b.addEventListener('click',()=>switchTab(b.dataset.tab)));$$('[data-open-tab]').forEach(a=>a.addEventListener('click',()=>setTimeout(()=>switchTab(a.dataset.openTab),80)));
function uuid(){return globalThis.crypto?.randomUUID?.()||String(Date.now()+Math.random())}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function addBill(data={name:'',amount:0,months:1}){bills.push({id:data.id||uuid(),name:data.name||'',amount:Number(data.amount)||0,months:Math.max(1,Number(data.months)||1)});renderBillRows()}
function updateBill(id,key,val){const b=bills.find(x=>x.id===id);if(b)b[key]=val}
function renderBillRows(){const el=$('#billList');if(!bills.length){el.innerHTML='<div class="hint">Nog geen toekomstige rekeningen toegevoegd.</div>';return}el.innerHTML=bills.map((b,i)=>`<div class="billRow" data-id="${b.id}"><div class="billName"><span class="miniLabel">Naam</span><input class="inlineInput bill-name" value="${escapeHtml(b.name)}" placeholder="Bijv. autoverzekering"></div><div><span class="miniLabel">Bedrag</span><input class="inlineInput bill-amount" type="number" min="0" step="10" value="${b.amount||''}" placeholder="600"></div><div><span class="miniLabel">Over maanden</span><input class="inlineInput bill-months" type="number" min="1" max="60" step="1" value="${b.months}"></div><button class="btn dangerBtn removeBill" type="button" aria-label="Verwijder rekening ${i+1}">×</button></div>`).join('');$$('.billRow').forEach(row=>{const id=row.dataset.id;row.querySelector('.bill-name').addEventListener('input',e=>updateBill(id,'name',e.target.value));row.querySelector('.bill-amount').addEventListener('input',e=>updateBill(id,'amount',Math.max(0,Number(e.target.value)||0)));row.querySelector('.bill-months').addEventListener('input',e=>updateBill(id,'months',Math.max(1,Number(e.target.value)||1)));row.querySelector('.removeBill').addEventListener('click',()=>{bills=bills.filter(x=>x.id!==id);renderBillRows()})})}
$('#addBillBtn').addEventListener('click',()=>addBill());
const ids=['income1','income2','benefits','otherIncome','housing','energy','insurance','telecom','groceries','transport','subscriptions','debt','childcare','otherCosts','savings','monthlySavingGoal','nextIncomeDate'];
function formData(){const d={};ids.forEach(id=>d[id]=id==='nextIncomeDate'?($('#'+id).value||''):nonneg(id));d.bills=bills.map(b=>({id:b.id,name:b.name.trim(),amount:Math.max(0,Number(b.amount)||0),months:Math.max(1,Number(b.months)||1)}));return d}
function fillForm(d){if(!d)return;ids.forEach(id=>{if(!$('#'+id))return;$('#'+id).value=id==='nextIncomeDate'?(d[id]||''):(Number(d[id])||0)});bills=Array.isArray(d.bills)?d.bills.map(b=>({id:b.id||uuid(),name:b.name||'',amount:Number(b.amount)||0,months:Math.max(1,Number(b.months)||1)})):[];renderBillRows()}
function save(d){localStorage.setItem(KEY,JSON.stringify(d))}function read(){try{return JSON.parse(localStorage.getItem(KEY))}catch{return null}}
function daysUntil(dateStr){if(!dateStr)return null;const now=new Date();now.setHours(0,0,0,0);const d=new Date(dateStr+'T00:00:00');const diff=Math.ceil((d-now)/86400000);return Number.isFinite(diff)&&diff>=0?diff:null}
function calc(d){const income=d.income1+d.income2+d.benefits+d.otherIncome;const costMap={Wonen:d.housing,Energie:d.energy,Verzekeringen:d.insurance,Telecom:d.telecom,Boodschappen:d.groceries,Vervoer:d.transport,Abonnementen:d.subscriptions,Aflossingen:d.debt,Kinderen:d.childcare,Overig:d.otherCosts};const costs=Object.values(costMap).reduce((a,b)=>a+b,0);const room=income-costs;const reserve=d.bills.reduce((sum,b)=>sum+(b.amount>0?b.amount/Math.max(1,b.months):0),0);const safe=room-reserve-d.monthlySavingGoal;const daily=costs/30.44;const days=daily>0?d.savings/daily:0;const paydayDays=daysUntil(d.nextIncomeDate);const dailySpend=paydayDays!==null&&paydayDays>0?safe/paydayDays:null;const forecast=m=>d.savings+(room*m)-d.bills.reduce((sum,b)=>sum+(b.amount>0&&b.months<=m?b.amount:0),0)-(d.monthlySavingGoal*m);const largest=Object.entries(costMap).sort((a,b)=>b[1]-a[1])[0]||['—',0];return{income,costMap,costs,room,reserve,safe,daily,days,paydayDays,dailySpend,forecast,largest}}
function status(c){if(c.income<=0)return{label:'Nog invullen',cls:'',msg:'Vul eerst je huishouden in.'};if(c.safe<0)return{label:'Actie nodig',cls:'danger',msg:'Na je ingevoerde kosten, reserveringen en spaardoel blijft er volgens deze berekening te weinig over.'};if(c.safe<150)return{label:'Weinig ruimte',cls:'warn',msg:'Je houdt weinig vrije maandruimte over. Controleer vooral je grootste kosten en toekomstige rekeningen.'};return{label:'Op koers',cls:'',msg:'Op basis van je invoer houd je na kosten en reserveringen nog maandruimte over.'}}
function bestAction(d,c){if(c.safe<0)return['Bekijk eerst je grootste maandkosten','Je veilige bestedingsruimte is negatief. Begin met één grote categorie in plaats van alles tegelijk.'];if(c.reserve>0)return['Reserveer '+money(c.reserve)+' per maand','Dit is samen nodig om je ingevoerde toekomstige rekeningen op tijd op te vangen.'];if(c.days<14)return['Bouw eerst een kleine buffer op','Je huidige buffer dekt volgens deze berekening ongeveer '+Math.round(c.days)+' dagen normale maandkosten.'];if(d.subscriptions>=50)return['Controleer je abonnementen','Je hebt '+money(d.subscriptions)+' per maand ingevuld aan abonnementen. Kijk welke je echt gebruikt.'];return['Je hoeft vandaag niets groots te doen','Je basis ziet er op dit moment rustig uit. Blijf vooral je komende rekeningen bijhouden.']}
function validate(d,c){if(c.income<=0)return'Vul minimaal één netto inkomensbedrag groter dan €0 in.';if(c.costs>c.income*4)return'Controleer je bedragen: de maandkosten lijken uitzonderlijk hoog ten opzichte van het inkomen.';return''}
function renderAll(){const d=read();if(!d){renderEmpty();return}const c=calc(d),s=status(c),a=bestAction(d,c);$('#heroSafe').textContent=money(Math.max(0,c.safe));$('#heroDays').textContent=Math.max(0,Math.round(c.days))+' dagen';$('#heroStatus').textContent=s.label==='Op koers'?'Je zit op koers':'Bekijk je maandruimte';$('#heroAction').textContent=a[0];$('#heroActionText').textContent=a[1];$('#safeSpend').textContent=money(c.safe);$('#safeText').textContent=s.msg;$('#monthlyRoom').textContent=money(c.room);$('#reserveMonthly').textContent=money(c.reserve);$('#savingGoalOut').textContent=money(d.monthlySavingGoal);$('#bufferDays').textContent=Math.max(0,Math.round(c.days))+' dagen';$('#roomProgress').style.width=clamp((c.safe/Math.max(c.income,1))*100,0,100)+'%';$('#statusText').textContent=s.label;$('#statusDot').className='signal '+s.cls;$('#incomeTotal').textContent=money(c.income);$('#costTotal').textContent=money(c.costs);$('#largestCost').textContent=c.largest[1]>0?c.largest[0]+' · '+money(c.largest[1]):'—';$('#annualSubs').textContent=money(d.subscriptions*12);$('#bestAction').textContent=a[0];$('#daysToPayday').textContent=c.paydayDays===null?'—':c.paydayDays+' dagen';$('#dailySpend').textContent=c.dailySpend===null?'—':money(c.dailySpend)+'/dag';renderBreakdown(d,c);renderTimeline(d,c);renderOpportunities(d,c);renderScenarioBase();renderStress(d,c)}
function renderEmpty(){['heroSafe','safeSpend','monthlyRoom','reserveMonthly','savingGoalOut','incomeTotal','costTotal','annualSubs'].forEach(id=>$('#'+id).textContent='€ 0');$('#heroDays').textContent='0 dagen';$('#bufferDays').textContent='0 dagen';$('#dailySpend').textContent='—';$('#daysToPayday').textContent='—';$('#largestCost').textContent='—';$('#heroStatus').textContent='Vul je situatie in';$('#heroAction').textContent='Maak je persoonlijke overzicht';$('#heroActionText').textContent='Daarna worden alle onderdelen automatisch berekend.';$('#safeText').textContent='Vul eerst je gegevens in.';$('#statusText').textContent='Nog niet berekend';$('#statusDot').className='signal';$('#bestAction').textContent='Vul je gegevens in';$('#roomProgress').style.width='0%';$('#expenseBars').innerHTML='<div class="hint">Nog geen uitgaven om te tonen.</div>';$('#summaryList').innerHTML='<div class="listItem"><div><small>Status</small><b>Vul eerst je gegevens in</b></div></div>';$('#timeline').innerHTML='<article class="timeItem"><small>VOORUITBLIK</small><h3>Nog niet berekend</h3><p>Vul eerst je huishouden in bij Invullen.</p></article>';$('#opportunityList').innerHTML='<article class="opp"><div class="oppIcon">✓</div><div><strong>Nog geen analyse</strong><small>Vul eerst je huishouden in.</small></div></article>';$('#stressResult').textContent='Nog niet berekend';$('#stressText').textContent='Na je invoer test GRIP automatisch wat er gebeurt bij 10% minder inkomen.';renderScenarioBase()}
function renderBreakdown(d,c){const entries=Object.entries(c.costMap).filter(([,v])=>v>0).sort((a,b)=>b[1]-a[1]);$('#expenseBars').innerHTML=entries.length?entries.map(([k,v])=>`<div class="barRow"><small>${k}</small><div class="barTrack"><div class="barFill" style="width:${clamp(v/Math.max(c.costs,1)*100,2,100)}%"></div></div><div class="barValue">${money(v)}</div></div>`).join(''):'<div class="hint">Nog geen kosten ingevuld.</div>';$('#summaryList').innerHTML=[['Inkomsten',money(c.income)],['Maandkosten',money(c.costs)],['Maandruimte',money(c.room)],['Reserveringen',money(c.reserve)],['Spaardoel',money(d.monthlySavingGoal)],['Veilig te besteden',money(c.safe)]].map(([a,b])=>`<div class="listItem"><div><small>${a}</small><b>${b}</b></div></div>`).join('')}
function renderTimeline(d,c){const points=[1,3,6,12];$('#timeline').innerHTML=points.map(m=>{const v=c.forecast(m);const cls=v<0?'danger':v<500?'warn':'';const due=d.bills.filter(b=>b.amount>0&&b.months<=m);const extra=due.length?' Inclusief '+due.map(b=>(b.name||'rekening')+' '+money(b.amount)).join(', ')+'.':' Op basis van je huidige maandpatroon.';return`<article class="timeItem ${cls}"><small>OVER ${m} ${m===1?'MAAND':'MAANDEN'}</small><h3>${money(v)}</h3><p>${extra}</p></article>`}).join('')}
function renderOpportunities(d,c){let list=[];if(c.safe<0)list.push({id:'shortfall',icon:'!',title:'Pak eerst het verwachte tekort aan',text:'Je veilige bestedingsruimte is '+money(c.safe)+'. Begin bij '+c.largest[0]+'.',value:'prioriteit'});if(c.reserve>0)list.push({id:'reserve',icon:'🗓',title:'Zet rekeningpotjes klaar',text:'Reserveer samen '+money(c.reserve)+' per maand voor je ingevoerde toekomstige rekeningen.',value:money(c.reserve)+'/mnd'});if(d.subscriptions>=25)list.push({id:'subs',icon:'◫',title:'Controleer abonnementen',text:'Je hebt '+money(d.subscriptions)+' per maand ingevuld, oftewel '+money(d.subscriptions*12)+' per jaar.',value:money(d.subscriptions*12)+'/jr'});if(d.telecom>=70)list.push({id:'tel',icon:'◉',title:'Bekijk telecomkosten',text:'Controleer bundel, looptijd en gebruik voordat je iets wijzigt.',value:money(d.telecom)+'/mnd'});if(c.days<30)list.push({id:'buffer',icon:'🛟',title:'Bouw richting 30 dagen buffer',text:'Je huidige buffer dekt ongeveer '+Math.max(0,Math.round(c.days))+' dagen normale kosten.',value:'buffer'});if(c.income>0&&c.costs/c.income>.8)list.push({id:'ratio',icon:'%',title:'Veel van je inkomen gaat naar maandkosten',text:'Je maandkosten zijn ongeveer '+Math.round(c.costs/c.income*100)+'% van je ingevoerde inkomen.',value:'controleer'});if(!list.length)list=[{id:'calm',icon:'✓',title:'Geen urgente aandachtspunten gevonden',text:'Met de huidige invoer ziet GRIP geen groot direct aandachtspunt.',value:'rustig'}];let done=[];try{done=JSON.parse(localStorage.getItem(DONE))||[]}catch{};$('#opportunityList').innerHTML=list.map(o=>`<article class="opp ${done.includes(o.id)?'done':''}" data-opp="${o.id}"><div class="oppIcon">${o.icon}</div><div><strong>${o.title}</strong><small>${o.text}</small></div><div class="oppValue">${o.value}<br><button class="checkbtn" type="button">${done.includes(o.id)?'Heropen':'Markeer gedaan'}</button></div></article>`).join('');$$('.checkbtn').forEach(b=>b.addEventListener('click',()=>{const id=b.closest('.opp').dataset.opp;let arr=[];try{arr=JSON.parse(localStorage.getItem(DONE))||[]}catch{};arr=arr.includes(id)?arr.filter(x=>x!==id):[...arr,id];localStorage.setItem(DONE,JSON.stringify(arr));renderOpportunities(d,c);toast('Kans bijgewerkt')}))}
function renderScenarioBase(){const d=read();if(!d){$('#scenarioRoom').textContent='€ 0';$('#scenarioMonthlyDiff').textContent='€ 0';$('#scenarioYearDiff').textContent='€ 0';$('#scenarioMessage').textContent='Vul eerst je basisgegevens in en test daarna een scenario.';return}const c=calc(d);$('#scenarioRoom').textContent=money(c.safe);$('#scenarioMonthlyDiff').textContent=money(0);$('#scenarioYearDiff').textContent=money(0);$('#scenarioMessage').textContent='Dit is je huidige veilige maandruimte. Pas links een scenario aan.'}
function renderStress(d,c){const stressSafe=(c.income*.9)-c.costs-c.reserve-d.monthlySavingGoal;$('#stressResult').textContent='Bij 10% minder inkomen: '+money(stressSafe);$('#stressText').textContent=stressSafe<0?'In deze stresstest wordt je veilige maandruimte negatief.':'In deze stresstest blijft je veilige maandruimte positief.'}
$('#scenarioForm').addEventListener('submit',e=>{e.preventDefault();const d=read();if(!d){toast('Vul eerst je GRIP-overzicht in');return}const c=calc(d),inc=raw('incomeChange'),cost=raw('costChange'),one=nonneg('oneOff'),newSafe=c.safe+inc-cost,yearDiff=(inc-cost)*12-one;$('#scenarioRoom').textContent=money(newSafe);$('#scenarioMonthlyDiff').textContent=signed(inc-cost);$('#scenarioYearDiff').textContent=signed(yearDiff);$('#scenarioMessage').textContent=newSafe<0?'In dit scenario wordt je veilige maandruimte negatief.':newSafe<c.safe?'Je houdt in dit scenario minder ruimte over dan nu.':'Je houdt in dit scenario meer ruimte over dan nu.'});
$$('.preset').forEach(b=>b.addEventListener('click',()=>{const d=read();if(!d){toast('Vul eerst je gegevens in');return}const c=calc(d);if(b.dataset.preset==='incomeDown'){$('#incomeChange').value=Math.round(-c.income*.10);$('#costChange').value=0;$('#oneOff').value=0}else if(b.dataset.preset==='costUp'){$('#incomeChange').value=0;$('#costChange').value=Math.round(c.costs*.15);$('#oneOff').value=0}else{$('#incomeChange').value=0;$('#costChange').value=0;$('#oneOff').value=0}$('#scenarioForm').requestSubmit()}));
$('#budgetForm').addEventListener('submit',e=>{e.preventDefault();const d=formData(),c=calc(d),msg=validate(d,c),alert=$('#formAlert');if(msg){alert.textContent=msg;alert.classList.add('show');return}alert.classList.remove('show');save(d);renderAll();switchTab('today');toast('Je volledige GRIP is berekend')});
$('#saveOnlyBtn').addEventListener('click',()=>{const d=formData();save(d);toast('Lokaal opgeslagen')});
const demo={income1:2700,income2:1650,benefits:0,otherIncome:0,housing:1125,energy:210,insurance:260,telecom:85,groceries:600,transport:350,subscriptions:72,debt:0,childcare:0,otherCosts:180,savings:3200,monthlySavingGoal:250,nextIncomeDate:'',bills:[{name:'Autoverzekering',amount:720,months:6},{name:'Gemeentelijke lasten',amount:420,months:4}]};
function useDemo(){fillForm(demo);save(formData());renderAll();switchTab('today');toast('Voorbeeld geladen')}
$('#demoBtn').addEventListener('click',useDemo);$('#demoTop').addEventListener('click',()=>{useDemo();$('#app').scrollIntoView({behavior:'smooth'})});
$('#resetBtn').addEventListener('click',()=>{if(!confirm('Wil je alle lokaal opgeslagen GRIP-gegevens op dit apparaat wissen?'))return;localStorage.removeItem(KEY);localStorage.removeItem(DONE);$('#budgetForm').reset();bills=[];renderBillRows();renderEmpty();switchTab('setup');toast('Lokale gegevens gewist')});
$('#exportBtn').addEventListener('click',()=>{const d=read();if(!d){toast('Maak eerst je GRIP-overzicht');return}const c=calc(d);const rows=[['Onderdeel','Bedrag'],['Totale inkomsten',c.income],['Totale maandkosten',c.costs],['Maandruimte',c.room],['Reserveringen',c.reserve],['Spaardoel',d.monthlySavingGoal],['Veilig te besteden',c.safe],['Buffer',d.savings],['Rustbuffer dagen',Math.round(c.days)],['Abonnementen per jaar',d.subscriptions*12]];Object.entries(c.costMap).forEach(([k,v])=>rows.push([k,v]));d.bills.forEach(b=>rows.push(['Toekomstige rekening: '+(b.name||'Onbenoemd'),b.amount]));const csv=rows.map(r=>r.map(x=>'"'+String(x).replaceAll('"','""')+'"').join(';')).join('\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='mijn-grip-overzicht.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),500);toast('CSV geëxporteerd')});
$('#methodBtn').addEventListener('click',()=>$('#methodDialog').showModal());$('#closeMethod').addEventListener('click',()=>$('#methodDialog').close());$('#methodDialog').addEventListener('click',e=>{if(e.target===$('#methodDialog'))$('#methodDialog').close()});
const savedTheme=localStorage.getItem(THEME)||'light';document.documentElement.dataset.theme=savedTheme;function setThemeIcon(){$('#themeToggle').textContent=document.documentElement.dataset.theme==='light'?'☾':'☀'}setThemeIcon();$('#themeToggle').addEventListener('click',()=>{const next=document.documentElement.dataset.theme==='light'?'dark':'light';document.documentElement.dataset.theme=next;localStorage.setItem(THEME,next);setThemeIcon()});
const saved=read();if(saved)fillForm(saved);else renderBillRows();renderAll();
})();